In [2]:
import pandas as pd

# Örnek veri oluşturma (index: datetime formatında)
data = {'value': [10, 20, 30, 40, 50, 60, 70, 80],
        'other_column': [100, 200, 300, 400, 500, 600, 700, 800]}

index = pd.date_range(start='2023-08-01', periods=8, freq='D')
df = pd.DataFrame(data, index=index)

print(df)

            value  other_column
2023-08-01     10           100
2023-08-02     20           200
2023-08-03     30           300
2023-08-04     40           400
2023-08-05     50           500
2023-08-06     60           600
2023-08-07     70           700
2023-08-08     80           800


In [3]:
import pandas as pd

# Örnek veri oluşturma (index: datetime formatında)
data = {'value': [10, 20, 30, 40, 50, 60, 70, 80],
        'other_column': [100, 200, 300, 400, 500, 600, 700, 800]}

index = pd.date_range(start='2023-08-01', periods=8, freq='D')
df = pd.DataFrame(data, index=index)

# Tüm verileri 3 gün ileri kaydırma
shifted_df = df.shift(periods=3, fill_value=None)

print(shifted_df)

            value  other_column
2023-08-01    NaN           NaN
2023-08-02    NaN           NaN
2023-08-03    NaN           NaN
2023-08-04   10.0         100.0
2023-08-05   20.0         200.0
2023-08-06   30.0         300.0
2023-08-07   40.0         400.0
2023-08-08   50.0         500.0


In [4]:
import pandas as pd

# Örnek veri oluşturma (index: datetime formatında)
data = {'value': [10, 20, 30, 40, 50, 60, 70, 80],
        'other_column': [100, 200, 300, 400, 500, 600, 700, 800]}

index = pd.date_range(start='2023-08-01', periods=8, freq='D')
df = pd.DataFrame(data, index=index)

# 'value' sütununu 3 gün ileri kaydırma
df['value'] = df['value'].shift(3)

# Eğer 'value' sütununu 3 gün geri kaydırmak isterseniz:
# df['value'] = df['value'].shift(3)

print(df)

            value  other_column
2023-08-01    NaN           100
2023-08-02    NaN           200
2023-08-03    NaN           300
2023-08-04   10.0           400
2023-08-05   20.0           500
2023-08-06   30.0           600
2023-08-07   40.0           700
2023-08-08   50.0           800


---

In [5]:
import pandas as pd

data = {'value': [10, 20, 30, 40, 50, 60, 70, 80]}
index = pd.date_range(start='2023-08-01', periods=len(data['value']), freq='D')

df = pd.DataFrame(data, index=index)
print(df)

            value
2023-08-01     10
2023-08-02     20
2023-08-03     30
2023-08-04     40
2023-08-05     50
2023-08-06     60
2023-08-07     70
2023-08-08     80


In [6]:
import pandas as pd

data = {'other_column': [100, 200, 300, 400, 500, 600, 700, 800]}
index = pd.date_range(start='2023-08-01', periods=len(data['other_column']), freq='D')

other_column = pd.Series(data['other_column'], index=index)
print(other_column)


2023-08-01    100
2023-08-02    200
2023-08-03    300
2023-08-04    400
2023-08-05    500
2023-08-06    600
2023-08-07    700
2023-08-08    800
Freq: D, dtype: int64


In [7]:
import pandas as pd

# Örnek veri oluşturma (index: datetime formatında)
data = {'value': [10, 20, 30, 40, 50, 60, 70, 80]}
index = pd.date_range(start='2023-08-01', periods=len(data['value']), freq='D')

value_series = pd.Series(data['value'], index=index)
shifted_value_series = value_series.copy()
shifted_value_series.index = shifted_value_series.index + pd.DateOffset(days=3)

print(shifted_value_series)

2023-08-04    10
2023-08-05    20
2023-08-06    30
2023-08-07    40
2023-08-08    50
2023-08-09    60
2023-08-10    70
2023-08-11    80
dtype: int64


In [8]:
other_column

2023-08-01    100
2023-08-02    200
2023-08-03    300
2023-08-04    400
2023-08-05    500
2023-08-06    600
2023-08-07    700
2023-08-08    800
Freq: D, dtype: int64

In [9]:
df_concat = pd.concat([shifted_value_series,other_column ], axis=1)

In [10]:
df_concat

0      1
2023-08-01   NaN  100.0
2023-08-02   NaN  200.0
2023-08-03   NaN  300.0
2023-08-04  10.0  400.0
2023-08-05  20.0  500.0
2023-08-06  30.0  600.0
2023-08-07  40.0  700.0
2023-08-08  50.0  800.0
2023-08-09  60.0    NaN
2023-08-10  70.0    NaN
2023-08-11  80.0    NaN

In [11]:
# Örnek veri oluşturma
import numpy as np
np.random.seed(42)
date_rng = pd.date_range(start='2023-01-01', end='2023-08-01', freq='D')
data = np.sin(np.arange(len(date_rng))) + np.random.normal(0, 0.1, size=len(date_rng))
df = pd.DataFrame(data, columns=['value'], index=date_rng)

# Lag özellikleri oluşturma (önceki değerler)
for i in range(1, 8):
    df[f'lag_{i}'] = df['value'].shift(i)

In [12]:
df

value     lag_1     lag_2     lag_3     lag_4     lag_5  \
2023-01-01  0.049671       NaN       NaN       NaN       NaN       NaN   
2023-01-02  0.827645  0.049671       NaN       NaN       NaN       NaN   
2023-01-03  0.974066  0.827645  0.049671       NaN       NaN       NaN   
2023-01-04  0.293423  0.974066  0.827645  0.049671       NaN       NaN   
2023-01-05 -0.780218  0.293423  0.974066  0.827645  0.049671       NaN   
...              ...       ...       ...       ...       ...       ...   
2023-07-28  0.660573 -0.286926 -0.923138 -0.808680  0.064353  1.038690   
2023-07-29  1.381740  0.660573 -0.286926 -0.923138 -0.808680  0.064353   
2023-07-30  0.524808  1.381740  0.660573 -0.286926 -0.923138 -0.808680   
2023-07-31 -0.377491  0.524808  1.381740  0.660573 -0.286926 -0.923138   
2023-08-01 -0.902947 -0.377491  0.524808  1.381740  0.660573 -0.286926   

               lag_6     lag_7  
2023-01-01       NaN       NaN  
2023-01-02       NaN       NaN  
2023-01-03       NaN       NaN  
2023-01-04       NaN       NaN  
2023-01-05       NaN       NaN  
...              ...       ...  
2023-07-28  0.914724 -0.005812  
2023-07-29  1.038690  0.914724  
2023-07-30  0.064353  1.038690  
2023-07-31 -0.808680  0.064353  
2023-08-01 -0.923138 -0.808680  

[213 rows x 8 columns]

In [13]:
import numpy as np

In [14]:
X_liste = []

for i in range(10):
    X_liste.append(np.random.randint(1,100,size=(2, 5)))


In [15]:
arr = np.array(X_liste)
arr.shape

(10, 2, 5)

In [16]:
arr

array([[[76, 87, 15, 92, 98],
        [66, 32, 87, 63, 86]],

       [[51, 25, 58, 63, 62],
        [22, 58, 58, 86, 49]],

       [[52, 42, 70, 15, 54],
        [60, 97,  8, 53, 60]],

       [[ 5, 68,  6, 96, 94],
        [47, 99, 55, 40, 52]],

       [[16, 13, 30, 19, 17],
        [63, 19, 92, 58, 55]],

       [[90, 90, 62, 23,  9],
        [12,  1, 58,  1, 34]],

       [[96, 48, 89,  1, 16],
        [61, 64, 63, 69, 22]],

       [[93, 67, 76, 26, 16],
        [51, 86, 57, 29, 78]],

       [[92, 69, 47, 94, 62],
        [69, 76, 16, 90, 90]],

       [[48, 85, 39, 33, 94],
        [23, 10, 69, 34, 52]]])

In [17]:
for i in range(10, 0, -1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [18]:
import numpy as np
u = np.array([1,2,3,4,5,100,101,102,103])
u[5:]

array([100, 101, 102, 103])

In [19]:
u.shape

(9,)

In [20]:
w = np.array([[1, 2, 3]])

w.shape

(1, 3)

In [21]:
ar = np.array([[1],[7],[8]])

In [22]:
w.shape

(1, 3)

In [23]:
ar.shape

(3, 1)

In [24]:
wr = w.reshape(-1, 1)

In [25]:
uw = np.concatenate((ar, wr), axis = 0)
uw.shape

(6, 1)

In [26]:
u1 = np.array([[1,2,3]])
u2 = np.array([[10,20,30,4]])

np.concatenate((u1, u2), axis=1)

array([[ 1,  2,  3, 10, 20, 30,  4]])

In [27]:
u1 = np.array([[1],[2],[3]])
k1 = u1.reshape(1,-1)
k1

array([[1, 2, 3]])

In [28]:
# Örnek bir DataFrame oluşturalım
import pandas as pd
data = {'Feature1': [1, 2, 3],
        'Feature2': [4, 5, 6]}
pad = pd.DataFrame(data)

In [29]:
pad.iloc[0:1,:].values.shape

(1, 2)

In [30]:
u = pad.columns[0]
type(u)

str

In [31]:
import pandas as pd
import numpy as np

data = {
    'Column_A': np.random.randint(1, 100, 10),
    'Column_B': np.random.uniform(0, 1, 10),
    'Column_C': np.random.choice(['A', 'B', 'C'], 10),
    'Column_D': np.random.randn(10)
}

df = pd.DataFrame(data)
df

Column_A  Column_B Column_C  Column_D
0        95  0.943892        C  0.651391
1        10  0.944252        A  0.110300
2        19  0.867199        A -0.430025
3        58  0.636404        B  1.230211
4        96  0.800949        C -1.291224
5         1  0.677168        A  1.554923
6        69  0.573367        A -0.981200
7         4  0.128500        C -1.238231
8        16  0.811204        B -0.824651
9        24  0.820639        B  1.951280

In [ ]:
df.iloc[5:]

In [32]:
target = df.columns[1]
df.loc[3:6, [target]].values.reshape(1,-1).shape

(1, 4)

In [33]:
df.iloc[2:3, :] # 4x1

Column_A  Column_B Column_C  Column_D
2        19  0.867199        A -0.430025

In [34]:
df_u = df.sort_index(ascending=False).reset_index(drop=True)

In [35]:

df_u.loc[5, ['Column_A']].values.shape

(1,)

In [37]:
np.array([[1.26129096e-02, 1.50468435e-02, 1.44900714e-02, 1.04060393e-02,
        1.13500635e-02, 8.44333989e-03, 4.35308682e-03, 3.00936870e-03,
        3.13689750e-03, 5.26911688e-03, 3.60502152e-03, 2.78386045e-03,
        3.69211437e-03, 1.34682858e-03, 2.97048797e-04, 0.00000000e+00,
        2.98604026e-04, 4.62525195e-03, 6.83212233e-03, 7.12917112e-03,
        1.31774579e-02, 9.67663672e-03, 1.14418220e-02, 1.11307761e-02,
        1.24013985e-02, 8.30181402e-03, 8.78704556e-03, 5.57083136e-03,
        9.84304626e-03, 7.43555130e-03, 9.11830940e-03, 7.47598726e-03,
        9.03121656e-03, 1.00327842e-02, 8.57553438e-03, 8.92701620e-03,
        8.65796153e-03, 1.20592480e-02, 1.17761963e-02, 1.15444671e-02,
        1.16533332e-02, 5.83210989e-03, 6.03117924e-03, 5.73101998e-03,
        4.06692463e-03, 6.36710877e-03, 5.32821559e-03, 5.58793889e-03,
        6.18514694e-03, 5.86165924e-03, 6.98453480e-03, 4.87719909e-03,
        4.79010625e-03, 5.46507577e-03, 5.17580312e-03, 5.37487247e-03,
        5.33910220e-03, 5.32199467e-03, 5.08404459e-03, 3.32974594e-03,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        5.46429887e-01, 4.18646635e-01, 5.21350997e-01]]).shape

(1, 75)

In [3]:
import numpy as np

arr = np.random.random(size=(3,5))
arr

array([[0.74420593, 0.99210943, 0.03152881, 0.88749718, 0.67774564],
       [0.23074554, 0.40856636, 0.65447172, 0.13287174, 0.92080236],
       [0.25188307, 0.79633646, 0.76746077, 0.88418924, 0.82881416]])

In [7]:
arr[]

array([], shape=(0, 5), dtype=float64)