In [3]:
dic = {'loss': [0.6908962726593018, 1.0678764581680298], 'precision': [0.4483985900878906, 0.2933333218097687], 'recall': [0.02139582298696041, 0.00373577862046659]}

import pandas as pd

dic = pd.DataFrame(dic)

dic.iloc[2,-1]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [6]:
import numpy as np

arr = np.array([1, 0, 0, 1, 1, 0, 0, 1, 0])

# Başlangıçta boş bir liste tanımla
np.unique(arr)

2

In [1]:
from datetime import datetime, timedelta

# Başlangıç ve bitiş tarihlerini tanımlayın
start_date = "2022-03-01"
end_date = "2023-09-01"

# Tarihleri datetime nesnelerine dönüştürün
start_datetime = datetime.strptime(start_date, "%Y-%m-%d")
end_datetime = datetime.strptime(end_date, "%Y-%m-%d")

# Her bir mum çubuğunun süresi (15 dakika) olduğunu düşünün
interval_minutes = 15

# Her bir mum çubuğunun süresini timedelta olarak hesaplayın
interval_timedelta = timedelta(minutes=interval_minutes)

# Başlangıç ve bitiş tarihleri arasındaki süreyi hesaplayın
time_delta = end_datetime - start_datetime

# Mum çubukları sayısını hesaplayın
num_candles = time_delta.total_seconds() / (interval_minutes * 60)

print("Toplam", int(num_candles), "adet 15 dakikalık mum çubuğu elde edersiniz.")


Toplam 52704 adet 15 dakikalık mum çubuğu elde edersiniz.


In [2]:

for j in range(5):
    for i in range(10):
        if i > j:
            print('It is broken')
            break
        else:
            print(i)
    print(f"{j}. loop for first loop is done\n")

    if j == 4: 
        print('J is broken')
        break

    
print('loop is done')

0
It is broken
0. loop for first loop is done

0
1
It is broken
1. loop for first loop is done

0
1
2
It is broken
2. loop for first loop is done

0
1
2
3
It is broken
3. loop for first loop is done

0
1
2
3
4
It is broken
4. loop for first loop is done

J is broken
loop is done


In [3]:
import pandas as pd

df_btc_minute = pd.read_csv('btc_min_data\BTC-2017min.csv')
df_btc_minute

FileNotFoundError: [Errno 2] No such file or directory: 'btc_min_data\\BTC-2017min.csv'

In [ ]:
import pandas as pd

# Örnek veri oluşturma (index: datetime formatında)
data = {'value': [10, 20, 30, 40, 50, 60, 70, 80],
        'other_column': [100, 200, 300, 400, 500, 600, 700, 800]}

index = pd.date_range(start='2023-08-01', periods=8, freq='D')
df = pd.DataFrame(data, index=index)

print(df)

            value  other_column
2023-08-01     10           100
2023-08-02     20           200
2023-08-03     30           300
2023-08-04     40           400
2023-08-05     50           500
2023-08-06     60           600
2023-08-07     70           700
2023-08-08     80           800


In [ ]:
liste = [100,500,1000,800,750,1200,2000,1800,1900,1650,1000,550,670,700,450,200,250,450,150,50,30,40,75,150,100]
len(liste)

25

In [ ]:
import numpy as np
arr = np.array(liste)

std = arr.std()
mean = arr.mean()

arr_scaled = np.array([])

for org_data in arr:
    scaled_data = (org_data - mean) / std
    arr_scaled = np.append(arr_scaled, scaled_data)

In [ ]:
arr_scaled

array([-0.9217475 , -0.26639912,  0.55278636,  0.22511217,  0.14319362,
        0.88046055,  2.19115731,  1.86348312,  2.02732022,  1.61772748,
        0.55278636, -0.18448057,  0.01212395,  0.06127507, -0.34831766,
       -0.7579104 , -0.67599185, -0.34831766, -0.83982895, -1.00366604,
       -1.03643346, -1.02004975, -0.96270677, -0.83982895, -0.9217475 ])

In [4]:
import pandas as pd
df1 = pd.DataFrame(data=liste, columns=['org_values'])

df2 = pd.DataFrame(data=arr_scaled, columns=['scaled_values'])

df = pd.concat([df1, df2], axis = 1)
df

NameError: name 'liste' is not defined

In [ ]:
df.loc[4, 'scaled_values']

0.14319362114686499

In [17]:
u = 'hey'
print(f'{u}')

hey


In [19]:
import numpy as np

u = np.array([1,2,3])
w = np.array([4])

np.concatenate([u,w])

array([1, 2, 3, 4])

In [16]:
from time import time
# Başlangıç zamanını kaydet
start_time = time()

# Burada programınızı çalıştırın
# Örnek olarak, bir işlem yapabilirsiniz
for i in range(100000): 
    i = i * i * i * i * i * i
    

# Bitiş zamanını kaydet
end_time = time()

# Çalışma süresini hesapla
u = end_time - start_time


float

In [22]:
import pandas as pd

# Örnek veri oluşturma (index: datetime formatında)
data = {'value': [10, 20, 30, 40, 50, 60, 70, 80],
        'other_column': [100, 200, 300, 400, 500, 600, 700, 800]}

index = pd.date_range(start='2023-08-01', periods=8, freq='D')
df = pd.DataFrame(data, index=index)

# Tüm verileri 3 gün ileri kaydırma
shifted_df = df.shift(periods=3, fill_value=None)

shifted_df = shifted_df[['other_column', 'value']]
shifted_df

other_column  value
2023-08-01           NaN    NaN
2023-08-02           NaN    NaN
2023-08-03           NaN    NaN
2023-08-04         100.0   10.0
2023-08-05         200.0   20.0
2023-08-06         300.0   30.0
2023-08-07         400.0   40.0
2023-08-08         500.0   50.0

In [71]:
import pandas as pd

# Örnek veri oluşturma (index: datetime formatında)
data = {'value': [10, 20, 30, 40, 50, 60, 70, 80],
        'other_column': [100, 200, 300, 400, 500, 600, 700, 800]}

index = pd.date_range(start='2023-08-01', periods=8, freq='D')
df = pd.DataFrame(data, index=index)

# 'value' sütununu 3 gün ileri kaydırma
df['value'] = df['value'].shift(3)

# Eğer 'value' sütununu 3 gün geri kaydırmak isterseniz:
# df['value'] = df['value'].shift(3)

print(df)

            value  other_column
2023-08-01    NaN           100
2023-08-02    NaN           200
2023-08-03    NaN           300
2023-08-04   10.0           400
2023-08-05   20.0           500
2023-08-06   30.0           600
2023-08-07   40.0           700
2023-08-08   50.0           800


---

In [2]:
import numpy as np

# Örnek olasılıksal tahminler (0.7 olasılıkla sınıf 1, 0.3 olasılıkla sınıf 0)
y_pred_probs = np.array([[0.3], [0.7], [0.4]])

# Eşik değeri belirle (örneğin, 0.5)
threshold = 0.5

# Olasılıksal değerleri eşik değere göre 1 ve 0'a dönüştür
y_pred_binary = (y_pred_probs >= threshold).astype(int)

print("Kesin sınıf tahminleri:")
print(y_pred_binary)



Kesin sınıf tahminleri:
[[0]
 [1]
 [0]]


In [72]:
import pandas as pd

data = {'value': [10, 20, 30, 40, 50, 60, 70, 80]}
index = pd.date_range(start='2023-08-01', periods=len(data['value']), freq='D')

df = pd.DataFrame(data, index=index)
print(df)

            value
2023-08-01     10
2023-08-02     20
2023-08-03     30
2023-08-04     40
2023-08-05     50
2023-08-06     60
2023-08-07     70
2023-08-08     80


In [73]:
import pandas as pd

data = {'other_column': [100, 200, 300, 400, 500, 600, 700, 800]}
index = pd.date_range(start='2023-08-01', periods=len(data['other_column']), freq='D')

other_column = pd.Series(data['other_column'], index=index)
print(other_column)


2023-08-01    100
2023-08-02    200
2023-08-03    300
2023-08-04    400
2023-08-05    500
2023-08-06    600
2023-08-07    700
2023-08-08    800
Freq: D, dtype: int64


In [74]:
import pandas as pd

# Örnek veri oluşturma (index: datetime formatında)
data = {'value': [10, 20, 30, 40, 50, 60, 70, 80]}
index = pd.date_range(start='2023-08-01', periods=len(data['value']), freq='D')

value_series = pd.Series(data['value'], index=index)
shifted_value_series = value_series.copy()
shifted_value_series.index = shifted_value_series.index + pd.DateOffset(days=3)

print(shifted_value_series)

2023-08-04    10
2023-08-05    20
2023-08-06    30
2023-08-07    40
2023-08-08    50
2023-08-09    60
2023-08-10    70
2023-08-11    80
dtype: int64


In [75]:
other_column

2023-08-01    100
2023-08-02    200
2023-08-03    300
2023-08-04    400
2023-08-05    500
2023-08-06    600
2023-08-07    700
2023-08-08    800
Freq: D, dtype: int64

In [76]:
df_concat = pd.concat([shifted_value_series,other_column ], axis=1)

In [77]:
df_concat

0      1
2023-08-01   NaN  100.0
2023-08-02   NaN  200.0
2023-08-03   NaN  300.0
2023-08-04  10.0  400.0
2023-08-05  20.0  500.0
2023-08-06  30.0  600.0
2023-08-07  40.0  700.0
2023-08-08  50.0  800.0
2023-08-09  60.0    NaN
2023-08-10  70.0    NaN
2023-08-11  80.0    NaN

In [78]:
# Örnek veri oluşturma
import numpy as np
np.random.seed(42)
date_rng = pd.date_range(start='2023-01-01', end='2023-08-01', freq='D')
data = np.sin(np.arange(len(date_rng))) + np.random.normal(0, 0.1, size=len(date_rng))
df = pd.DataFrame(data, columns=['value'], index=date_rng)

# Lag özellikleri oluşturma (önceki değerler)
for i in range(1, 8):
    df[f'lag_{i}'] = df['value'].shift(i)

In [79]:
df

value     lag_1     lag_2     lag_3     lag_4     lag_5  \
2023-01-01  0.049671       NaN       NaN       NaN       NaN       NaN   
2023-01-02  0.827645  0.049671       NaN       NaN       NaN       NaN   
2023-01-03  0.974066  0.827645  0.049671       NaN       NaN       NaN   
2023-01-04  0.293423  0.974066  0.827645  0.049671       NaN       NaN   
2023-01-05 -0.780218  0.293423  0.974066  0.827645  0.049671       NaN   
...              ...       ...       ...       ...       ...       ...   
2023-07-28  0.660573 -0.286926 -0.923138 -0.808680  0.064353  1.038690   
2023-07-29  1.381740  0.660573 -0.286926 -0.923138 -0.808680  0.064353   
2023-07-30  0.524808  1.381740  0.660573 -0.286926 -0.923138 -0.808680   
2023-07-31 -0.377491  0.524808  1.381740  0.660573 -0.286926 -0.923138   
2023-08-01 -0.902947 -0.377491  0.524808  1.381740  0.660573 -0.286926   

               lag_6     lag_7  
2023-01-01       NaN       NaN  
2023-01-02       NaN       NaN  
2023-01-03       NaN       NaN  
2023-01-04       NaN       NaN  
2023-01-05       NaN       NaN  
...              ...       ...  
2023-07-28  0.914724 -0.005812  
2023-07-29  1.038690  0.914724  
2023-07-30  0.064353  1.038690  
2023-07-31 -0.808680  0.064353  
2023-08-01 -0.923138 -0.808680  

[213 rows x 8 columns]

In [80]:
import numpy as np

In [81]:
X_liste = []

for i in range(10):
    X_liste.append(np.random.randint(1,100,size=(2, 5)))


In [82]:
arr = np.array(X_liste)
arr.shape

(10, 2, 5)

In [83]:
arr

array([[[76, 87, 15, 92, 98],
        [66, 32, 87, 63, 86]],

       [[51, 25, 58, 63, 62],
        [22, 58, 58, 86, 49]],

       [[52, 42, 70, 15, 54],
        [60, 97,  8, 53, 60]],

       [[ 5, 68,  6, 96, 94],
        [47, 99, 55, 40, 52]],

       [[16, 13, 30, 19, 17],
        [63, 19, 92, 58, 55]],

       [[90, 90, 62, 23,  9],
        [12,  1, 58,  1, 34]],

       [[96, 48, 89,  1, 16],
        [61, 64, 63, 69, 22]],

       [[93, 67, 76, 26, 16],
        [51, 86, 57, 29, 78]],

       [[92, 69, 47, 94, 62],
        [69, 76, 16, 90, 90]],

       [[48, 85, 39, 33, 94],
        [23, 10, 69, 34, 52]]])

In [84]:
for i in range(10, 0, -1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [85]:
import numpy as np
u = np.array([1,2,3,4,5,100,101,102,103])
u[5:]

array([100, 101, 102, 103])

In [86]:
u.shape

(9,)

In [87]:
w = np.array([[1, 2, 3]])

w.shape

(1, 3)

In [88]:
ar = np.array([[1],[7],[8]])

In [89]:
w.shape

(1, 3)

In [90]:
ar.shape

(3, 1)

In [91]:
wr = w.reshape(-1, 1)

In [92]:
uw = np.concatenate((ar, wr), axis = 0)
uw.shape

(6, 1)

In [14]:
import pandas as pd
dic = {'loss': [0.6908962726593018, 1.0678764581680298], 'precision': [0.4483985900878906, 0.2933333218097687], 'recall': [0.02139582298696041, 0.00373577862046659]}

import numpy


<function dict.values>

In [93]:
u1 = np.array([[1,2,3]])
u2 = np.array([[10,20,30,4]])

np.concatenate((u1, u2), axis=1)

array([[ 1,  2,  3, 10, 20, 30,  4]])

In [94]:
u1 = np.array([[1],[2],[3]])
k1 = u1.reshape(1,-1)
k1

array([[1, 2, 3]])

In [95]:
# Örnek bir DataFrame oluşturalım
import pandas as pd
data = {'Feature1': [1, 2, 3],
        'Feature2': [4, 5, 6]}
pad = pd.DataFrame(data)

In [96]:
pad.iloc[0:1,:].values.shape

(1, 2)

In [97]:
u = pad.columns[0]
type(u)

str

In [5]:
import pandas as pd
import numpy as np

data = {
    'Column_A': np.random.randint(1, 100, 10),
    'Column_B': np.random.uniform(0, 1, 10),
    'Column_C': np.random.choice(['A', 'B', 'C'], 10),
    'Column_D': np.random.randn(10)
}

df = pd.DataFrame(data)
df

Column_A  Column_B Column_C  Column_D
0        85  0.206045        C -0.117609
1        16  0.872664        A -0.748150
2        20  0.053939        A -0.041208
3        69  0.185024        A -0.846686
4        32  0.482089        A -1.087228
5        26  0.918029        A -0.433086
6        85  0.080007        A -2.088938
7        47  0.767514        C -0.594199
8        33  0.624745        A  0.723558
9        14  0.340121        B  1.990852

In [9]:
df.loc[-1,['Column_D']]

KeyError: -1

In [99]:
df.iloc[5:]

Column_A  Column_B Column_C  Column_D
5         1  0.677168        A  1.554923
6        69  0.573367        A -0.981200
7         4  0.128500        C -1.238231
8        16  0.811204        B -0.824651
9        24  0.820639        B  1.951280

In [100]:
target = df.columns[1]
df.loc[3:6, [target]].values.reshape(1,-1).shape

(1, 4)

In [101]:
df.iloc[2:3, :] # 4x1

Column_A  Column_B Column_C  Column_D
2        19  0.867199        A -0.430025

In [102]:
df_u = df.sort_index(ascending=False).reset_index(drop=True)

In [103]:

df_u.loc[5, ['Column_A']].values.shape

(1,)

In [104]:
np.array([[1.26129096e-02, 1.50468435e-02, 1.44900714e-02, 1.04060393e-02,
        1.13500635e-02, 8.44333989e-03, 4.35308682e-03, 3.00936870e-03,
        3.13689750e-03, 5.26911688e-03, 3.60502152e-03, 2.78386045e-03,
        3.69211437e-03, 1.34682858e-03, 2.97048797e-04, 0.00000000e+00,
        2.98604026e-04, 4.62525195e-03, 6.83212233e-03, 7.12917112e-03,
        1.31774579e-02, 9.67663672e-03, 1.14418220e-02, 1.11307761e-02,
        1.24013985e-02, 8.30181402e-03, 8.78704556e-03, 5.57083136e-03,
        9.84304626e-03, 7.43555130e-03, 9.11830940e-03, 7.47598726e-03,
        9.03121656e-03, 1.00327842e-02, 8.57553438e-03, 8.92701620e-03,
        8.65796153e-03, 1.20592480e-02, 1.17761963e-02, 1.15444671e-02,
        1.16533332e-02, 5.83210989e-03, 6.03117924e-03, 5.73101998e-03,
        4.06692463e-03, 6.36710877e-03, 5.32821559e-03, 5.58793889e-03,
        6.18514694e-03, 5.86165924e-03, 6.98453480e-03, 4.87719909e-03,
        4.79010625e-03, 5.46507577e-03, 5.17580312e-03, 5.37487247e-03,
        5.33910220e-03, 5.32199467e-03, 5.08404459e-03, 3.32974594e-03,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        5.46429887e-01, 4.18646635e-01, 5.21350997e-01]]).shape

(1, 75)

In [105]:
import numpy as np

arr = np.random.random(size=(3,5))
arr

array([[0.3483366 , 0.93664815, 0.03918633, 0.41794603, 0.96758055],
       [0.54797188, 0.42347094, 0.56852028, 0.57592458, 0.73164776],
       [0.12768973, 0.25001645, 0.58054401, 0.86711661, 0.56186669]])

In [106]:
arr[]

SyntaxError: invalid syntax (1326972886.py, line 1)

In [1]:
import numpy as np

In [2]:
arr = [12,32,43]
new = 1

arr = np.append(arr,new)
arr

array([12, 32, 43,  1])

In [3]:
ep = np.array([])

In [4]:
liste1 = np.array([1,2,3])
liste2 = np.array([10,20,30,40,50,60,70])
ep = np.append(ep, np.concatenate([liste1, liste2]))


In [5]:
liste1 = np.array([5,6,7])
liste2 = np.array([11,12,13,14,15,16,17])

ep = np.append(ep, np.concatenate([liste1, liste2]))


In [8]:
ep = ep.reshape(2, 10)

In [10]:
ep

array([[ 1.,  2.,  3., 10., 20., 30., 40., 50., 60., 70.],
       [ 5.,  6.,  7., 11., 12., 13., 14., 15., 16., 17.]])

In [11]:
ep[:, -1:]

array([[70.],
       [17.]])

In [1]:
import numpy as np
np.random.seed(32)

liste1 = [1,2,3]
liste2 = [10,20,30,40,50,60,70]
arr = np.array([])

for i in range(10):
    l1 = np.random.randint(1,50,size=(1,2))
    l2 = np.random.randint(100,150,size=(1,2))
    arr = np.append(arr, np.concatenate([l1,l2], axis=1))
u = arr.reshape(10,4)
u

array([[ 24.,  44., 105., 124.],
       [ 20.,   8., 125., 103.],
       [ 38.,  43., 109., 104.],
       [ 12.,  18., 103., 101.],
       [ 35.,  36., 124., 142.],
       [ 19.,  11., 120., 136.],
       [ 37.,   6., 138., 113.],
       [ 12.,  12., 126., 129.],
       [ 30.,  27., 147., 100.],
       [ 12.,   7., 146., 130.]])

In [1]:
import pandas 
df = pandas.DataFrame(data = u, columns=(['col1', 'col2', 'col3', 'col4']))
df['index'] = df.index
df_1 = df.sort_values(by='col2', ascending=True)
df_1['col2_score'] = range(len(df_1))

NameError: name 'u' is not defined

In [4]:
import pandas as pd
pred_df = pd.DataFrame(index=range(10), columns=['bear','volatile', 'bull', 'change', 'investment'])

pred_df.iloc[0,0] = 1

In [5]:
pred_df

bear volatile bull change investment
0    1      NaN  NaN    NaN        NaN
1  NaN      NaN  NaN    NaN        NaN
2  NaN      NaN  NaN    NaN        NaN
3  NaN      NaN  NaN    NaN        NaN
4  NaN      NaN  NaN    NaN        NaN
5  NaN      NaN  NaN    NaN        NaN
6  NaN      NaN  NaN    NaN        NaN
7  NaN      NaN  NaN    NaN        NaN
8  NaN      NaN  NaN    NaN        NaN
9  NaN      NaN  NaN    NaN        NaN

In [3]:
df_1

col1  col2   col3   col4  index  col2_score
6  37.0   6.0  138.0  113.0      6           0
9  12.0   7.0  146.0  130.0      9           1
1  20.0   8.0  125.0  103.0      1           2
5  19.0  11.0  120.0  136.0      5           3
7  12.0  12.0  126.0  129.0      7           4
3  12.0  18.0  103.0  101.0      3           5
8  30.0  27.0  147.0  100.0      8           6
4  35.0  36.0  124.0  142.0      4           7
2  38.0  43.0  109.0  104.0      2           8
0  24.0  44.0  105.0  124.0      0           9

In [112]:
df_1.columns[1:].to_list() + df_1.columns[0:1].to_list()

['col2', 'col3', 'col4', 'index_', 'col2_score', 'col1']

In [117]:
df_1[df_1.columns[-1:].tolist() + df.columns[:-1].tolist()]

col2_score  col1  col2   col3   col4
6           0  37.0   6.0  138.0  113.0
9           1  12.0   7.0  146.0  130.0
1           2  20.0   8.0  125.0  103.0
5           3  19.0  11.0  120.0  136.0
7           4  12.0  12.0  126.0  129.0
3           5  12.0  18.0  103.0  101.0
8           6  30.0  27.0  147.0  100.0
4           7  35.0  36.0  124.0  142.0
2           8  38.0  43.0  109.0  104.0
0           9  24.0  44.0  105.0  124.0

In [4]:
df_1['total'] = df_1['col1'] + df_1['col2'] + df_1['col3'] + df_1['col4']

In [5]:
df_1

col1  col2   col3   col4  col2_score  total
6  37.0   6.0  138.0  113.0           0  294.0
9  12.0   7.0  146.0  130.0           1  295.0
1  20.0   8.0  125.0  103.0           2  256.0
5  19.0  11.0  120.0  136.0           3  286.0
7  12.0  12.0  126.0  129.0           4  279.0
3  12.0  18.0  103.0  101.0           5  234.0
8  30.0  27.0  147.0  100.0           6  304.0
4  35.0  36.0  124.0  142.0           7  337.0
2  38.0  43.0  109.0  104.0           8  294.0
0  24.0  44.0  105.0  124.0           9  297.0

In [6]:
de1 = [1,2,3]
de2 = [30,40]

for de1 in de1:
    for de2 in de2:
        print(de1 + de2)

31
41


TypeError: 'int' object is not iterable